---
name: Scan with Detekt

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - ".github/workflows/detekt.yaml"
      - "detekt.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "src/**"
      - ".github/workflows/detekt.yaml"
      - "detekt.yml"
  schedule:
    - cron: "0 13 * * 6"
  workflow_dispatch:

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: current
      - name: Run Detekt
        run: ./gradlew detektAll
