---
name: misspell
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: reviewdog/action-misspell@d6429416b12b09b4e2768307d53bef58d172e962
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"
